server:
  port: ${PORT:80}
  https: ${SSL_SERVER:false}
  compression:
    enabled: true
  cors:
    origins: ${CORS_ORIGINS:*}
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  data:
    rest:
      base-path: /api/v1
  # DATABASE
  datasource: # docker run -it --rm --name postgres -p 5432:5432 -e POSTGRES_DB=quizz -e POSTGRES_PASSWORD=wQ9b0cIsls65 postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PG_HOST:db.nocturlab.fr}:${PG_PORT:5432}/${PG_DATABASE:quizz}
    username: ${PG_LOGIN:quizz}
    password: ${PG_PASS:wQ9b0cIsls65}
  # JPA / HIBERNATE
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      id:
        new_generator_mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
