name: Springboot CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build -x test
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: release
        path: ./build/libs/
    - name: Run tests
      run: ./gradlew test
      continue-on-error: true # Allow tests to fail (will be removed when test will be correctly implemented)
    - name: Publish to Docker
      if:  matrix.os == 'ubuntu-latest'
      uses: elgohr/Publish-Docker-Github-Action@1.12
      with:
        name: nocturlab/archi-data
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: false
        cache: true
    - name: Publish on production server
      if: github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@v0.0.2
      env:
        HOST: ${{ secrets.SSH_HOST }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        args: --user ${{ secrets.SSH_USER }} --script "'docker stack rm quizz'" --script "'docker pull nocturlab/quizz'" --script "'docker stack deploy -c ${{ secrets.STACK_DIR }} quizz'"
    - name: Publish on beta server
      if: github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@v0.0.2
      env:
        HOST: ${{ secrets.SSH_HOST }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        args: --user ${{ secrets.SSH_USER }} --script "'docker stack rm quizz-beta'" --script "'docker pull nocturlab/quizz:beta'" --script "'docker stack deploy -c ${{ secrets.BETA_STACK_DIR }} quizz-beta'"
    - name: Release
      uses: toolmantim/release-drafter@v5.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
